### PR TITLE
Support dynamic protocols

### PR DESCRIPTION
**Pull request by refaelyehuda**

### CODE REVIEW

**Comment by eelkram** [comment]
The change looks good.  @refaelyehuda  can you bump the version in the AssemblyInfo.cs file to 0.5.  If @joshburt thinks it looks good we'll merge it in.

**Comment by refaelyehuda** [comment]
The version was increased @eelkram

**Review by joshburt — APPROVED** [review]
I've finished reviewing the changes, and everything looks good!

**Comment by refaelyehuda** [comment]
Thanks

**Pull request merged**
